<!DOCTYPE peliculas [
    <!ELEMENT peliculas (pelicula+)>
    <!ELEMENT pelicula (titulo,director,autor,actores*)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT director (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT actores (actor|actriz)+>
    <!ELEMENT actor (#PCDATA)>
    <!ELEMENT actriz (#PCDATA)>
]>
<peliculas>
    <pelicula>
        <titulo>
            Con faldas y a lo loco
        </titulo>
        <director>
            Billy wilder
        </director>
        <autor>
            autor
        </autor>
        <actores>
            <actor>
                Tony Curtis
            </actor>
            <actor>
                Jack Lemmon
            </actor>
            <actriz>
                Marilyn Monroe
            </actriz>
        </actores>
    </pelicula>
    <pelicula>
        <titulo>
            sopa de ganso
        </titulo>
        <director>
            Leo McCarey
        </director>
        <autor>
            autor
        </autor>
    </pelicula>
</peliculas>
